//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.06 at 02:08:36 PM CST 
//


package com.escuela.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.escuela.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.escuela.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PostAgregarAlumnoRequest }
     * 
     */
    public PostAgregarAlumnoRequest createPostAgregarAlumnoRequest() {
        return new PostAgregarAlumnoRequest();
    }

    /**
     * Create an instance of {@link Alumno }
     * 
     */
    public Alumno createAlumno() {
        return new Alumno();
    }

    /**
     * Create an instance of {@link PostAgregarAlumnoResponse }
     * 
     */
    public PostAgregarAlumnoResponse createPostAgregarAlumnoResponse() {
        return new PostAgregarAlumnoResponse();
    }

    /**
     * Create an instance of {@link GetMostrarAlumnosRequest }
     * 
     */
    public GetMostrarAlumnosRequest createGetMostrarAlumnosRequest() {
        return new GetMostrarAlumnosRequest();
    }

    /**
     * Create an instance of {@link GetMostrarAlumnosResponse }
     * 
     */
    public GetMostrarAlumnosResponse createGetMostrarAlumnosResponse() {
        return new GetMostrarAlumnosResponse();
    }

    /**
     * Create an instance of {@link GetBuscarAlumnoRequest }
     * 
     */
    public GetBuscarAlumnoRequest createGetBuscarAlumnoRequest() {
        return new GetBuscarAlumnoRequest();
    }

    /**
     * Create an instance of {@link GetBuscarAlumnoResponse }
     * 
     */
    public GetBuscarAlumnoResponse createGetBuscarAlumnoResponse() {
        return new GetBuscarAlumnoResponse();
    }

    /**
     * Create an instance of {@link DeleteAlumnoRequest }
     * 
     */
    public DeleteAlumnoRequest createDeleteAlumnoRequest() {
        return new DeleteAlumnoRequest();
    }

    /**
     * Create an instance of {@link DeleteAlumnoResponse }
     * 
     */
    public DeleteAlumnoResponse createDeleteAlumnoResponse() {
        return new DeleteAlumnoResponse();
    }

    /**
     * Create an instance of {@link UpdateAlumnoRequest }
     * 
     */
    public UpdateAlumnoRequest createUpdateAlumnoRequest() {
        return new UpdateAlumnoRequest();
    }

    /**
     * Create an instance of {@link UpdateAlumnoResponse }
     * 
     */
    public UpdateAlumnoResponse createUpdateAlumnoResponse() {
        return new UpdateAlumnoResponse();
    }

}
